image:
  file: .gitpod.Dockerfile

tasks:
  - name: Aufgabe 7
    init: javac BinTree.java
    command: java BinTree
  - name: Javadoc
    command: javadoc -d doc BinTree.java
  - name: Javadoc Server
    command: |
      cd doc
      python3 -m http.server 3000

vscode:
  extensions:
    - vscjava.vscode-java-pack
