name: Compile and Run on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Java Version
        run: java -version

      - name: Compile and Run
        run: |
          javac BinTree.java
          java BinTree
